language: go
go:
- 1.13
install:
- curl -sSL https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64
  -o ${GOPATH}/bin/test-reporter
- chmod +x ${GOPATH}/bin/test-reporter
- go get ./...
before_script:
- test-reporter before-build
script:
- go test -v -coverprofile c.out -coverpkg ./...
after_script:
- test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT